import type { Metadata } from "next";
import PageHero from "@/components/PageHero";
import Reveal from "@/components/Reveal";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "Disclaimer covering the use of Metabob Private Limited's website, app, and generative AI services.",
};

const sections = [
  {
    title: "1. General information",
    body: "The information provided on the Metabob Private Limited website is for general informational purposes only. While we strive to keep content accurate and up to date, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, or availability of the website or the information, services, or related graphics contained on it.",
  },
  {
    title: "2. No professional advice",
    body: "Content on this website — including product descriptions, case studies, and blog content — is provided for general guidance and does not constitute legal, financial, or professional advice specific to your use case. You should consult a qualified professional before making decisions based on information found on our site.",
  },
  {
    title: "3. Nature of AI-generated content",
    body: "Images and videos produced by Metabob are generated by machine learning models and may occasionally be inaccurate, unexpected, or not reflect reality — including generating anatomically implausible details, stylistic artifacts, or content that does not match the prompt's intent. You are responsible for reviewing generated content before using it for any commercial, editorial, or public-facing purpose.",
  },
  {
    title: "4. Results and case studies",
    body: "Metrics, turnaround times, and outcomes referenced on this website, including in testimonials and case studies, reflect specific customer circumstances and are not a guarantee of similar results for every user. Generation speed and output quality can vary based on prompt complexity, plan tier, and platform load.",
  },
  {
    title: "5. Third-party links and infrastructure",
    body: "Our website may contain links to third-party websites not owned or controlled by Metabob Private Limited. We have no control over, and assume no responsibility for, the content or practices of third-party sites. Our platform also depends on third-party cloud and hardware providers, including AWS and NVIDIA hardware partners; we are not responsible for outages or changes originating from these providers.",
  },
  {
    title: "6. User responsibility for generated content",
    body: "You are solely responsible for ensuring that prompts you submit and content you generate comply with applicable law and our Terms & Conditions, including restrictions on generating content that infringes third-party rights or depicts real people without consent.",
  },
  {
    title: "7. No guarantee of uninterrupted service",
    body: "While we target high availability for our generation infrastructure, we do not guarantee that our website, app, or API will be uninterrupted, timely, secure, or error-free at all times.",
  },
  {
    title: "8. Limitation of liability",
    body: "To the fullest extent permitted by law, Metabob Private Limited disclaims all liability for any loss or damage arising from reliance on information provided on this website, from generated content, or from the use of, or inability to use, this website or our services, beyond what is set out in our Terms & Conditions.",
  },
  {
    title: "9. Views and opinions",
    body: "Any opinions expressed in blog content, articles, or resources on this website are those of the individual authors and do not necessarily reflect the official policy or position of Metabob Private Limited.",
  },
  {
    title: "10. Changes to this disclaimer",
    body: "We may update this Disclaimer periodically. Material changes will be posted on this page with an updated revision date.",
  },
  {
    title: "11. Governing law",
    body: "This Disclaimer is governed by the laws of India, with courts in Bengaluru, Karnataka having exclusive jurisdiction over any related disputes.",
  },
  {
    title: "12. Contact us",
    body: "Questions about this Disclaimer can be directed to hello@metabob.in, by phone at +91 91234 56789, or by post to 4th Floor, Prestige Tech Park, Kadubeesanahalli, Bengaluru, Karnataka 560103, India.",
  },
];

export default function DisclaimerPage() {
  return (
    <div>
      <PageHero
        eyebrow="Legal"
        title="Disclaimer"
        description="Last updated: 16 July 2026. Please read this disclaimer carefully before using our website or services."
      />
      <section className="py-20">
        <div className="mx-auto max-w-3xl px-6">
          <div className="hairline-t">
            {sections.map((section, i) => (
              <Reveal key={section.title} delay={Math.min(i * 30, 150)} className="hairline-b py-8">
                <h2 className="font-display text-xl text-paper">{section.title}</h2>
                <p className="mt-3 text-sm leading-relaxed text-muted">{section.body}</p>
              </Reveal>
            ))}
          </div>
          <p className="mt-8 text-sm text-muted">
            Questions about this disclaimer can be sent to{" "}
            <a href="mailto:hello@metabob.in" className="text-accent hover:underline">
              hello@metabob.in
            </a>
            .
          </p>
        </div>
      </section>
    </div>
  );
}
